{{- if and (eq .Values.cluster.hpa "yes") (eq .Values.cluster.deployTo "eks") }}
#Refer to README for more details on HPA
{{- if has "dataplanecpuutilizationpct" .Values.custom_metrics }}
apiVersion: metrics.aws/v1alpha1
kind: ExternalMetric
metadata:
  name: dataplanecpuutilizationpct
  namespace: kube-system
spec:
  name: dataplanecpuutilizationpct
  resource:
    resource: "deployment"
  queries:
    - id: dataplanecpuutilizationpct
      metricStat:
        metric:
          namespace: {{ .Values.pan_namespace_eks }}
          metricName: "dataplanecpuutilizationpct"
        period: 300
        stat: Average
        unit: Count
      returnData: true
{{- end }}

{{- if has "dataplanepacketbufferutilization" .Values.custom_metrics }}
apiVersion: metrics.aws/v1alpha1
kind: ExternalMetric
metadata:
  name: dataplanepacketbufferutilization
  namespace: kube-system
spec:
  name: dataplanepacketbufferutilization
  resource:
    resource: "deployment"
  queries:
    - id: dataplanepacketbufferutilization
      metricStat:
        metric:
          namespace: {{ .Values.pan_namespace_eks }}
          metricName: "dataplanepacketbufferutilization"
        period: 300
        stat: Average
        unit: Count
      returnData: true
{{- end }}

{{- if has "pansessionactive" .Values.custom_metrics }}
apiVersion: metrics.aws/v1alpha1
kind: ExternalMetric
metadata:
  name: pansessionactive
  namespace: kube-system
spec:
  name: pansessionactive
  resource:
    resource: "deployment"
  queries:
    - id: pansessionactive
      metricStat:
        metric:
          namespace: {{ .Values.pan_namespace_eks }}
          metricName: "pansessionactive"
        period: 300
        stat: Average
        unit: Count
      returnData: true
{{- end }}

{{- if has "pansessionutilization" .Values.custom_metrics }}
apiVersion: metrics.aws/v1alpha1
kind: ExternalMetric
metadata:
  name: pansessionutilization
  namespace: kube-system
spec:
  name: pansessionutilization
  resource:
    resource: "deployment"
  queries:
    - id: pansessionutilization
      metricStat:
        metric:
          namespace: {{ .Values.pan_namespace_eks }}
          metricName: "pansessionutilization"
        period: 300
        stat: Average
        unit: Count
      returnData: true
{{- end }}

{{- if has "pansessionsslproxyutilization" .Values.custom_metrics }}
apiVersion: metrics.aws/v1alpha1
kind: ExternalMetric
metadata:
  name: pansessionsslproxyutilization
  namespace: kube-system
spec:
  name: pansessionsslproxyutilization
  resource:
    resource: "deployment"
  queries:
    - id: pansessionsslproxyutilization
      metricStat:
        metric:
          namespace: {{ .Values.pan_namespace_eks }}
          metricName: "pansessionsslproxyutilization"
        period: 300
        stat: Average
        unit: Count
      returnData: true
{{- end }}

{{- if has "panthroughput" .Values.custom_metrics }}
apiVersion: metrics.aws/v1alpha1
kind: ExternalMetric
metadata:
  name: panthroughput
  namespace: kube-system
spec:
  name: panthroughput
  resource:
    resource: "deployment"
  queries:
    - id: panthroughput
      metricStat:
        metric:
          namespace: {{ .Values.pan_namespace_eks }}
          metricName: "panthroughput"
        period: 300
        stat: Average
        unit: Count
      returnData: true
{{- end }}

{{- if has "panpacketrate" .Values.custom_metrics }}
apiVersion: metrics.aws/v1alpha1
kind: ExternalMetric
metadata:
  name: panpacketrate
  namespace: kube-system
spec:
  name: panpacketrate
  resource:
    resource: "deployment"
  queries:
    - id: panpacketrate
      metricStat:
        metric:
          namespace: {{ .Values.pan_namespace_eks }}
          metricName: "panpacketrate"
        period: 300
        stat: Average
        unit: Count
      returnData: true
{{- end }}

{{- if has "panconnectionspersecond" .Values.custom_metrics }}
apiVersion: metrics.aws/v1alpha1
kind: ExternalMetric
metadata:
  name: panconnectionspersecond
  namespace: kube-system
spec:
  name: panconnectionspersecond
  resource:
    resource: "deployment"
  queries:
    - id: panconnectionspersecond
      metricStat:
        metric:
          namespace: {{ .Values.pan_namespace_eks }}
          metricName: "panconnectionspersecond"
        period: 300
        stat: Average
        unit: Count
      returnData: true
{{- end }}

{{- if has "pandataplaneslots" .Values.custom_metrics }}
apiVersion: metrics.aws/v1alpha1
kind: ExternalMetric
metadata:
  name: pandataplaneslots
  namespace: kube-system
spec:
  name: pandataplaneslots
  resource:
    resource: "statefulset"
  queries:
    - id: pandataplaneslots
      metricStat:
        metric:
          namespace: {{ .Values.pan_namespace_eks }}
          metricName: "pandataplaneslots"
        period: 300
        stat: Average
        unit: Count
      returnData: true
{{- end }}

{{- if has "panloggingrate" .Values.custom_metrics }}
apiVersion: metrics.aws/v1alpha1
kind: ExternalMetric
metadata:
  name: panloggingrate
  namespace: kube-system
spec:
  name: panloggingrate
  resource:
    resource: "statefulset"
  queries:
    - id: panloggingrate
      metricStat:
        metric:
          namespace: {{ .Values.pan_namespace_eks }}
          metricName: "panloggingrate"
        period: 300
        stat: Average
        unit: Count
      returnData: true
{{- end }}
{{- end }}