{{- if eq .Values.cluster.hpa "yes" }}

#Refer to README for more details on HPA
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta2
metadata:
  name: hpa-dp-eks
  namespace: kube-system
spec:
  scaleTargetRef:
    {{- if eq .Values.cluster.deployTo "aks" }}
    apiVersion: apps/v1
    {{- end }}
    {{- if eq .Values.cluster.deployTo "gke" }}
    apiVersion: apps/v1
    {{- end }}
    {{- if eq .Values.cluster.deployTo "eks" }}
    apiVersion: apps/v1beta1
    {{- end }}
    kind: Deployment
  name: pan-ngfw-dep
  minReplicas: {{ .Values.dp.min_replicas }} # Ensure to change this "minReplicas" to same as "replicas" in pan-cn-ngfw.yaml
  maxReplicas: 30
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Pods
        value: 1
        periodSeconds: 60
      - type: Percent
        value: 1
        periodSeconds: 60
      selectPolicy: Max
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Pods
        value: 1
        periodSeconds: 300 # assuming 5 mins for dp to be ready
      - type: Percent
        value: 1
        periodSeconds: 300 # assuming 5 mins for dp to be ready
      selectPolicy: Max
  {{- if (eq .Values.cluster.deployTo "eks") }}    
  metrics:
  - type: External
    external:
      metric:
        name: dataplanecpuutilizationpct
      target:
        type: Value
        value: {{ .Values.eks_dataplanecpuutilizationpct_target_value }}
  {{- end }}
  {{- if eq .Values.cluster.deployTo "aks" }}
  metrics:
  - type: Pods
    pods:
      metric:
       name: pansessionactive
      target:
        type: AverageValue
        averageValue: {{ .Values.aks_pansessionactive_average_value }}
  {{- end }}
  {{- if eq .Values.cluster.deployTo "gke" }}
  metrics:
  - type: External
    external:
      metric:
        name: custom.googleapis.com|cnseries|{{ .Values.hpa_name }}|dataplanecpuutilizationpct
      target:
        type: Value
        value: {{ .Values.gke_dataplanecpuutilizationpct_target_value }}
  - type: External
    external:
      metric:
        name: custom.googleapis.com|cnseries|{{ .Values.hpa_name }}|dataplanepacketbufferutilization
      target:
        type: Value
        value: {{ .Values.gke_dataplanepacketbufferutilization_target_value }}
  - type: External
    external:
      metric:
        name: custom.googleapis.com|cnseries|{{ .Values.hpa_name }}|pansessionactive
      target:
        type: Value
        value: {{ .Values.gke_pansessionactive_target_value }}
  - type: External
    external:
      metric:
        name: custom.googleapis.com|cnseries|{{ .Values.hpa_name }}|pansessionutilization
      target:
        type: Value
        value: {{ .Values.gke_pansessionutilization_target_value }}
  - type: External
    external:
      metric:
        name: custom.googleapis.com|cnseries|{{ .Values.hpa_name }}|pansessionsslproxyutilization
      target:
        type: Value
        value: {{ .Values.gke_pansessionsslproxyutilization_target_value }}
  - type: External
    external:
      metric:
        name: custom.googleapis.com|cnseries|{{ .Values.hpa_name }}|panthroughput
      target:
        type: Value
        value: {{ .Values.gke_panthroughput_target_value }}
  - type: External
    external:
      metric:
        name: custom.googleapis.com|cnseries|{{ .Values.hpa_name }}|panpacketrate
      target:
        type: Value
        value: {{ .Values.gke_panpacketrate_target_value }}
  - type: External
    external:
      metric:
        name: custom.googleapis.com|cnseries|{{ .Values.hpa_name }}|panconnectionspersecond
      target:
        type: Value
        value: {{ .Values.gke_panconnectionspersecond_target_value }}
  {{- end }}        
{{- end }}