apiVersion: v1
kind: ConfigMap
metadata:
  name: pan-mgmt-config-1
  namespace: kube-system
data:
  PAN_SERVICE_NAME: pan-mgmt-svc-1
  PAN_MGMT_SECRET: pan-mgmt-secret
  {{- if  .Values.cluster.ha  }}
  PAN_HA_SUPPORT: "true"
  PAN_HA_PRIORITY:  {{ .Values.cluster.ha_1_priority | quote }}
  {{- else }}	
  #PAN_HA_SUPPORT: "true"
  {{- end }}

  # Panorama settings
  PAN_PANORAMA_IP: {{ required "A value must be provided for .Values.panorama.ip" .Values.panorama.ip | quote }}
  {{- if .Values.panorama.ip2 }}
  PAN_PANORAMA_IP2: {{ .Values.panorama.ip2 | quote }}
  {{- end }}
  PAN_DEVICE_GROUP: {{ required "A value must be provided for .Values.panorama.deviceGroup" .Values.panorama.deviceGroup | quote }}	
  PAN_TEMPLATE_STACK: {{ required "A value must be provided for .Values.panorama.template" .Values.panorama.template | quote }}	
  PAN_CGNAME: {{ required "A value must be provided for .Values.panorama.cgName" .Values.panorama.cgName | quote }}
  PAN_CTNR_MODE_TYPE: "k8s-cnf"

#Non-mandatory parameters
  # Recommended to have same name as the cluster name provided in Panorama Kubernetes plugin - helps with easier identification of pods if managing multiple clusters with same Panorama
  #CLUSTER_NAME: "<Cluster name>"

  #PAN_PANORAMA_IP2: ""

  # Comment out to use CERTs otherwise PSK for IPSec between pan-mgmt and pan-ngfw
  {{- if eq .Values.cluster.deployTo "openshift" }}
  # Not using CERTs currently in openshift
  IPSEC_CERT_BYPASS: ""         # No values needed
  {{- else }}
  # IPSEC_CERT_BYPASS: ""         # No values needed
  {{- end }}

  {{- if .Values.pan_jumbo_frame_enabled }}
  # Override auto-detect of jumbo-frame mode and force enable system-wide
  PAN_JUMBO_FRAME_ENABLED: {{ .Values.pan_jumbo_frame_enabled | quote }}
  {{- end }}  

  {{- if .Values.pan_gtp_enabled }}
  # Start MGMT pod with GTP enabled. For complete functionality, need GTP 
  # enable at Panorama as well.
  PAN_GTP_ENABLED: {{ .Values.pan_gtp_enabled | quote }}
  {{- end }}

  {{- if .Values.pan_sctp_enabled }}
  # Start MGMT pod with GTP enabled. For complete functionality, need GTP 
  # enable at Panorama as well.
  PAN_SCTP_ENABLED: {{ .Values.pan_sctp_enabled | quote }}
  {{- end }}
  
  {{- if .Values.pan_ngfw_memory }}
  # Enable high feature capacities. These need high memory for MGMT pod and
  # higher/matching memory than specified below for NGFW pod.
  # 6.5Gi : Maximum 2  DP supported
  # 42Gi  : Maximum 31 DP supported
  # 54Gi  : Maximum 47 DP supported
  PAN_NGFW_MEMORY: {{ .Values.pan_ngfw_memory | quote }}
  {{- end }}

  {{- if .Values.pan_data_mode }}
  # For enabling faster datapath - AF_XDP, default is AF_PACKETV2.
  # This requires kernel support and NGFW pod running with privileged: true
  PAN_DATA_MODE: {{ .Values.pan_data_mode | quote }}
  {{- end }}
  {{- if eq .Values.cluster.deployTo "eks" }}
  #Certificate signing
  PAN_CSR_SIGNER_NAME: "beta.eks.amazonaws.com/app-serving"
  {{- end }}
