apiVersion: v1
kind: ConfigMap
metadata:
  name: pan-ngfw-config-0
  namespace: kube-system
data:
  PAN_SERVICE_NAME: pan-mgmt-svc-0    # should match the pan-cn-mgmt.yaml's Service name            
  FAILOVER_MODE: {{ .Values.firewall.failoverMode }} # licensing failure behavior
  DP_RINGBUFFER: "60000"            # buffer count for memory/performance control
  PAN_CTNR_MODE_TYPE: "k8s-cnf"
  {{- if eq .Values.dp.pan_data_mode  "dpdk" }}
  PAN_DATA_MODE: "dpdk"            # HUGEPAGE_MEMORY_REQUEST is also needed
  HUGEPAGE_MEMORY_REQUEST:  {{ .Values.dp.hugepage_memory_request | quote }}  # in MB - needed for DPDK mode - should be same as hugepage request in pan-cn-ngfw.yaml - might change after 1.20
  {{- else }}	
  #PAN_DATA_MODE: "dpdk"            # HUGEPAGE_MEMORY_REQUEST is also needed
  {{- end }}

  {{- if  .Values.cluster.ha  }}
  PAN_HA_SUPPORT: "true"
  {{- else }}	
  #PAN_HA_SUPPORT: "true"
  {{- end }}

  # Comment out to use CERTs otherwise PSK for IPSec between pan-mgmt and pan-ngfw
  {{- if eq .Values.cluster.deployTo "openshift" }}
  # Not using CERTs currently in openshift
  IPSEC_CERT_BYPASS: ""             # No values needed
  {{- else }}
  #IPSEC_CERT_BYPASS: ""            # No values needed
  {{- end }}
  
  # Enable/Disable cpu pinning of the forwarding processes (default physical
  # cpus) (different from K8S cpu pinning of the pods)
  PAN_CPU_PINNING_ENABLED: {{ .Values.pan_cpu_pinning_enabled | quote }}

  {{- if .Values.pan_numa_enabled }}
  # When doing cpu pinning of forwarding processes, use single NUMA node
  PAN_NUMA_ENABLED: {{ .Values.pan_numa_enabled | quote }}
  {{- end }}
  {{- if .Values.pan_hyperthreading_enabled }}
  # When doing cpu pinning of forwarding processes, use logical cpus as well
  PAN_HYPERTHREADING_ENABLED: {{ .Values.pan_hyperthreading_enabled | quote }}
  {{- end }}
  {{- if .Values.pan_cpu_pinning_base }}   
  # When doing cpu pinning of forwarding processes, skip the lower numbered cpus
  # and start from this cpu
  PAN_CPU_PINNING_BASE: {{ .Values.pan_cpu_pinning_base | quote }}
  {{- end }}
