# Default values for cn-series.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# The K8s environment 
# Valid deployTo tags are: [gke|eks|aks|openshift|native]
cluster:
  deployTo: 

# Firewall tags
# Valid licenceBundle tags are: [basic|bundle1|bundle2] # License bundle valid only for 10.0.x PanOS versions
firewall:
  operationMode: daemonset
  failoverMode: failopen
  licenseBundle: bundle2

# Panorama tags
panorama:
  ip: 
  ip2: 
  authKey: 
  deviceGroup: 
  template: 
  cgName: 

# Customer Support Portal PIN information
csp:
  pinId: 
  pinValue: 
  alternateUrl: 
 
# MP container tags
mp:
  initImage:  docker.io/paloaltonetworks/pan_cn_mgmt_init
  initVersion: latest
  image: docker.io/paloaltonetworks/panos_cn_mgmt
  version: latest
  cpuLimit: 4

# DP container tags
dp:
  image: docker.io/paloaltonetworks/panos_cn_ngfw
  version: latest
  cpuLimit: 2

# CNI container tags
cni:
  image: docker.io/paloaltonetworks/pan_cni
  version: latest


############
# Non essential configs
############
imagePullSecrets: []
  # - name: myRegistryKeySecretName
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# service:
#   type: ClusterIP
#   port: 80

# ingress:
#   enabled: false
#   annotations: {}
#     # kubernetes.io/ingress.class: nginx
#     # kubernetes.io/tls-acme: "true"
#   hosts:
#     - host: chart-example.local
#       paths: []
#   tls: []
#   #  - secretName: chart-example-tls
#   #    hosts:
#   #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
