apiVersion: v1
kind: ConfigMap
metadata:
  name: pan-mgmt-config
  namespace: kube-system
data:
  PAN_SERVICE_NAME: pan-mgmt-svc
  PAN_MGMT_SECRET: pan-mgmt-secret

  # Panorama settings
  PAN_PANORAMA_IP: {{ required "A value must be provided for .Values.panorama.ip" .Values.panorama.ip }}
  {{- if .Values.panorama.ip2 }}
  PAN_PANORAMA_IP2: {{ .Values.panorama.ip2 }}
  {{- end }}
  PAN_DEVICE_GROUP: {{ required "A value must be provided for .Values.panorama.deviceGroup" .Values.panorama.deviceGroup }}	
  PAN_TEMPLATE_STACK: {{ required "A value must be provided for .Values.panorama.template" .Values.panorama.template }}	
  PAN_CGNAME: {{ required "A value must be provided for .Values.panorama.cgName" .Values.panorama.cgName }}

#Non-mandatory parameters
  # Recommended to have same name as the cluster name provided in Panorama Kubernetes plugin - helps with easier identification of pods if managing multiple clusters with same Panorama
  #CLUSTER_NAME: "<Cluster name>"

  #PAN_PANORAMA_IP2: ""
  
  # Comment out to use CERTs otherwise PSK for IPSec between pan-mgmt and pan-ngfw
  {{- if eq .Values.cluster.deployTo "openshift" }}
  # Not using CERTs currently in openshift
  IPSEC_CERT_BYPASS: ""         # No values needed
  {{- else }}
  # IPSEC_CERT_BYPASS: ""         # No values needed
  {{- end }}

  # Override auto-detect of jumbo-frame mode and force enable system-wide
  #PAN_JUMBO_FRAME_ENABLED: "true"
  
  # Start MGMT pod with GTP enabled. For complete functionality, need GTP 
  # enable at Panorama as well.
  #PAN_GTP_ENABLED: "true"
  
  # Enable high feature capacities. These need high memory for MGMT pod and
  # higher/matching memory than specified below for NGFW pod.
  #PAN_NGFW_MEMORY: "42Gi"

  # For enabling faster datapath - AF_XDP, default is AF_PACKETV2.
  # This requires kernel support and NGFW pod running with privileged: true
  #PAN_DATA_MODE: "next-gen"
