# Default values for cn-series as a dameon-set.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

##############################
# Mandatory Parameters
##############################

# The K8s environment 
# Valid deployTo tags are: [gke|eks|aks|openshift|native]
# Valid multus tags are : [enable|disable] Keep the multus as enable for openshift and native deployments.
# Valid tags for volumes for native deployment are : [static|dynamic]
cluster:
  deployTo: "eks"
  multus: "disable"
  volumes: "static"

# Firewall tags
firewall:
  failoverMode: "failopen"

# Panorama tags
panorama:
  ip: "<Panorama-IP>" 
  ip2: 
  authKey: "<Panorama-auth-key>"
  deviceGroup: "<Panorama-device-group>"
  template: "<panorama-template-stack>" 
  cgName: "<panorama-collector-group>"

# Customer Support Portal PIN information
csp:
  pinId: ""
  pinValue: "" 
  alternateUrl: "" 
 
# MP container tags
mp:
  initImage: gcr.io/pan-cn-series/pan_cn_mgmt_init
  initVersion: preferred
  image: gcr.io/pan-cn-series/panos_cn_mgmt
  version: preferred-10.2
  cpuLimit: 4
  memoryLimit: 4.0Gi

# DP container tags
dp:
  image: gcr.io/pan-cn-series/panos_cn_ngfw
  version: preferred-10.2
  cpuLimit: 1
  memoryLimit: 2.25Gi

# CNI container tags
cni:
  image: gcr.io/pan-cn-series/pan_cni
  version: preferred

##############################
# Non Mandatory Parameters
##############################

# Override auto-detect of jumbo-frame mode and force enable system-wide
# Valid tags are true | false
pan_jumbo_frame_enabled: "false"

# Start MGMT pod with GTP enabled. For complete functionality, need GTP 
# enable at Panorama as well.
# Valid tags are true | false
pan_gtp_enabled: "false"
  
# Enable high feature capacities. These need high memory for MGMT pod and
# higher/matching memory than specified below for NGFW pod.
pan_ngfw_memory: "2Gi" 

# For enabling faster datapath - AF_XDP, default is AF_PACKETV2.
# This requires kernel support and NGFW pod running with privileged: true
# Valid tags are "next-gen"
pan_data_mode: 

#Interfaces
#Update the list of interfaces that you would like to secure. By Default it is "eth0"
secureInterfaces: ["eth0"]

##################################
# Non essential configs
##################################
imagePullSecrets: 
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# service:
#   type: ClusterIP
#   port: 80

# ingress:
#   enabled: false
#   annotations: {}
#     # kubernetes.io/ingress.class: nginx
#     # kubernetes.io/tls-acme: "true"
#   hosts:
#     - host: chart-example.local
#       paths: []
#   tls: []
#   #  - secretName: chart-example-tls
#   #    hosts:
#   #      - chart-example.local

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
