apiVersion: v1
kind: Secret
metadata:
  name: pan-mgmt-secret
  namespace: kube-system
type: Opaque
stringData:
  # Panorama Auth Key
  PAN_PANORAMA_AUTH_KEY: {{ required "A value must be provided for .Values.panorama.authKey" .Values.panorama.authKey | quote }}
  {{- if and (.Values.csp.pinId) (.Values.csp.pinValue) }}
  # Thermite Certificate retrieval 
  CN-SERIES-AUTO-REGISTRATION-PIN-ID: {{ .Values.csp.pinId | quote }}
  CN-SERIES-AUTO-REGISTRATION-PIN-VALUE: {{ .Values.csp.pinValue | quote }}
  {{- else }}
  #CN-SERIES-AUTO-REGISTRATION-PIN-ID: 
  #CN-SERIES-AUTO-REGISTRATION-PIN-VALUE: 
  {{- end }}
#Non-mandatory parameters
  # Uncomment this for CSP overide 
  {{- if .Values.csp.alternateUrl }}
  CN-SERIES-AUTO-REGISTRATION-API-CSP: {{ .Values.csp.alternateUrl | quote }} 
  {{- else }}
  #CN-SERIES-AUTO-REGISTRATION-API-CSP: "<csp-url>" 
  {{- end }}
