#Creating cluster role, namespace role and service account for pan-mgmt
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pan-mgmt-crole
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "create", "list", "update", "delete"]
- apiGroups: ["certificates.k8s.io"]
  resources: ["certificatesigningrequests", "certificatesigningrequests/approval", "certificatesigningrequests/status"]
  verbs: ["get", "create", "list", "update", "delete"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pan-mgmt-crb-kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pan-mgmt-crole
subjects:
- kind: ServiceAccount
  name: pan-mgmt-sa
  namespace: {{ .Values.targetNamespace | default "kube-system" | quote }}
---


apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pan-mgmt-role
  namespace: {{ .Values.targetNamespace | default "kube-system" | quote }} # Should be namespace pan-mgmt is deployed in
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pan-mgmt-rb-kube-system
  namespace: {{ .Values.targetNamespace | default "kube-system" | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pan-mgmt-role
subjects:
- namespace: {{ .Values.targetNamespace | default "kube-system" | quote }}
  kind: ServiceAccount
  name: pan-mgmt-sa
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: pan-mgmt-sa
  namespace: {{ .Values.targetNamespace | default "kube-system" | quote }}
