apiVersion: v1
kind: Secret
metadata:
  name: pan-mgmt-secret
  namespace: kube-system
type: Opaque
stringData:
 # Panorama Auth Key
  PAN_PANORAMA_AUTH_KEY: {{ .Values.panorama.authKey | quote }}
  # Thermite Certificate retrieval 
  # CN-SERIES-AUTO-REGISTRATION-PIN-ID: {{ .Values.csp.pidId | quote }}
  # CN-SERIES-AUTO-REGISTRATION-PIN-VALUE: {{ .Values.csp.pinValue | quote }}
#Non-mandatory parameters
  # Uncomment this for CSP overide 
  {{- if .Values.csp.alternateUrl }}
  CN-SERIES-AUTO-REGISTRATION-API-CSP: {{ .Values.csp.alternateUrl | quote }} 
  {{- else }}
  #CN-SERIES-AUTO-REGISTRATION-API-CSP: "<csp-url>" 
  {{- end }}
